' Developer Express Code Central Example:
' LINQ to XPO
' 
' LINQ is .NET Language-Integrated Query
' (http://msdn2.microsoft.com/en-us/library/bb308959.aspx). It's included in .NET
' Framework 3.5 and you can use it in Visual Studio 2008 projects.
' XPO officially
' supports LINQ since v7.3. This example provides several sample queries to help
' you get started with LINQ to XPO.
' See
' Also:
' http://www.devexpress.com/scid=K18051
' The LINQ project
' (http://msdn2.microsoft.com/en-us/netframework/aa904594.aspx)
' 
' You can find sample updates and versions for different programming languages here:
' http://www.devexpress.com/example=E642
'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.1433
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------
Namespace XpoLinqNorthwindSample.Properties

    ''' <summary>
    '''   A strongly-typed resource class, for looking up localized strings, etc.
    ''' </summary>
    ' This class was auto-generated by the StronglyTypedResourceBuilder
    ' class via a tool like ResGen or Visual Studio.
    ' To add or remove a member, edit your .ResX file then rerun ResGen
    ' with the /str option, or rebuild your VS project.
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")>
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>
    <Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>
    Friend Class Resources

        Private Shared resourceMan As Global.System.Resources.ResourceManager

        Private Shared resourceCulture As Global.System.Globalization.CultureInfo

        <Global.System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")>
        Friend Sub New()
        End Sub

        ''' <summary>
        '''   Returns the cached ResourceManager instance used by this class.
        ''' </summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>
        Friend Shared ReadOnly Property ResourceManager As Global.System.Resources.ResourceManager
            Get
                If(XpoLinqNorthwindSample.Properties.Resources.resourceMan Is Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("XpoLinqNorthwindSample.Properties.Resources", GetType(XpoLinqNorthwindSample.Properties.Resources).Assembly)
                    XpoLinqNorthwindSample.Properties.Resources.resourceMan = temp
                End If

                Return XpoLinqNorthwindSample.Properties.Resources.resourceMan
            End Get
        End Property

        ''' <summary>
        '''   Overrides the current thread's CurrentUICulture property for all
        '''   resource lookups using this strongly typed resource class.
        ''' </summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>
        Friend Shared Property Culture As Global.System.Globalization.CultureInfo
            Get
                Return XpoLinqNorthwindSample.Properties.Resources.resourceCulture
            End Get

            Set(ByVal value As Global.System.Globalization.CultureInfo)
                XpoLinqNorthwindSample.Properties.Resources.resourceCulture = value
            End Set
        End Property
    End Class
End Namespace
