' Developer Express Code Central Example:
' LINQ to XPO
' 
' LINQ is .NET Language-Integrated Query
' (http://msdn2.microsoft.com/en-us/library/bb308959.aspx). It's included in .NET
' Framework 3.5 and you can use it in Visual Studio 2008 projects.
' XPO officially
' supports LINQ since v7.3. This example provides several sample queries to help
' you get started with LINQ to XPO.
' See
' Also:
' http://www.devexpress.com/scid=K18051
' The LINQ project
' (http://msdn2.microsoft.com/en-us/netframework/aa904594.aspx)
' 
' You can find sample updates and versions for different programming languages here:
' http://www.devexpress.com/example=E642
'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.1433
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------
Namespace XpoLinqNorthwindSample.Properties

    <Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "9.0.0.0")>
    Friend NotInheritable Partial Class Settings
        Inherits Global.System.Configuration.ApplicationSettingsBase

        Private Shared defaultInstance As XpoLinqNorthwindSample.Properties.Settings = CType((Global.System.Configuration.ApplicationSettingsBase.Synchronized(New XpoLinqNorthwindSample.Properties.Settings())), XpoLinqNorthwindSample.Properties.Settings)

        Public Shared ReadOnly Property [Default] As Settings
            Get
                Return XpoLinqNorthwindSample.Properties.Settings.defaultInstance
            End Get
        End Property
    End Class
End Namespace
